apiVersion : apps/v1
kind: Deployment
metadata:
  name: username 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: username
  template:
    metadata:
      labels:
        app: username 
    spec:
      containers:
        - name: username 
          image: myregs.azurecr.io/username:26
          env:
          - name : DB_URL
            valueFrom: 
              secretKeyRef:
                name: db-credentials
                key: DB_URL
          - name : DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key : DB_USERNAME
          - name : DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PASSWORD
          - name: DB_PORT
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DB_PORT
